# -*- coding: utf-8 -*-
"""project 77.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19KNHX_5kC3AT80GIal0ktYtLQFzucU8V

### Instructions

#### Goal of the Project

In class 77, you would have explored the surface plot which is a kind of three-dimensional plot used to visualise the behaviour of  three-dimensional data. And we can use it to observe the relationship between three variables of an equation.

This project is designed for you to practice and solve the activities that are based on the concepts covered in the lesson:

**Logistic Regression - Surface Plot and Partial Derivatives.**

---

### Activities



In this project, you need to plot the equations mentioned in the activities on the graph using the surface plot.

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

     https://colab.research.google.com/drive/15_kCFpLr13tnRBKZWhtXrwWULx0_DIdD

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project77** format.

4. Now, write your code in the prescribed code cells.

---

### Activities

A surface plot is a kind of three-dimensional plot used to visualise the behaviour of a three-dimensional data. Thus, we can use it to observe the relationship between three variables of an equation.

In this project, you need to plot the equations mentioned in the activities on the graph using the surface plot.

---

####Activity 1: Create a Surface Plot for the Hypotenuse


Create a surface plot for calculating the hypotenuse of the `n` right-angled triangle(s) using the formula:
$$hypotenuse = \sqrt{(length)^2 + (width)^2}$$

Here,
* `length` will be an array of `n` numbers ranging from 1 to 5.
* `width` will be an array of `n` numbers ranging from 5 to 10.
* `n=100` (number of triangles).

**Steps:**
1. Create a variable `n` to store the number of triangles.
2. Create two 1D arrays using `np.linspace()` to store the length and width.
3. Create a meshed grid using `length` and `width` arrays using `np.meshgrid()`.

  This will return two 2D arrays. Store these 2D arrays in `meshed_length` and  `meshed_width` variables.
4. Create a 3D plot using `gca(projection = '3d')` function and store this 3D axis in `ax` variable.
5. Plot the 3D surface plot for the hypotenuse using `plot_surface()` function.
 - Plot the `length` on X-axis.
 - Plot the `width` on Y-axis.
 - Calculate the hypotenuse using the formula and plot it on the Z-axis.

6. Label all the three-axis and display the plot.
"""

# Code to ignore warning
import warnings
warnings.filterwarnings('ignore')

# Create the surface plot for calculating Hypotenuse
# Import the modules
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D

# Create variables n, length, width
n=100
length = np.linspace(1,5,n)
width = np.linspace(5,10,n)

# Create the mesh grid
meshed_length,meshed_width = np.meshgrid(length,width)

# Create the graph using figure(), title(), gca() functions
fig = plt.figure(figsize=(20,5),dpi = 96)
ax = fig.gca(projection ='3d')
plt.title('Surface plot for the hypotenuse')

# Plot the surface plot for the hypotenuse
ax.plot_surface(meshed_length,meshed_width,np.array(np.sqrt(meshed_length**2+meshed_width**2)))

# Label the axes
ax.set(xlabel='Length',ylabel='Width',zlabel='Hypotenuse')

# Display the surface plot
plt.show()

"""---

####Activity 2: Create a surface plot for two equations

Create a surface plot for observing the two equations given below for `m` number of inputs

* **Equation 1:** $z = (a+b)^2$
* **Equation 2:** $z = a^2 + b^2$

Here,

* `a` will be an array of `m` numbers ranging from 0 to 5.
* `b` will be an array of `m` numbers ranging from 0 to 5.
* `m = 100` (number of inputs).
"""

# Create the surface plot for the equations
# Create variables m, a, b
m = 100
a = np.linspace(0,5,m)
b = np.linspace(0,5,m)

# Create the mesh grid for a and b
meshed_a,meshed_b = np.meshgrid(a,b)

# Create the graph figure(), title(), and gca() functions
fig = plt.figure(figsize = (20,5),dpi = 96)
ax = fig.gca(projection = '3d')
plt.title('Surface plot for two equations')

# Plot the surface plot for equation 1. The meshed_a will be on X-axis, meshed_b on Y-axis and the equation 1 will be on Z-axis.
ax.plot_surface(meshed_a,meshed_b,np.array((meshed_a+meshed_b)**2))


# Plot the surface plot for equation 2. The meshed_a will be on X-axis, meshed_b on Y-axis and the equation 2 will be on Z-axis.
ax.plot_surface(meshed_a,meshed_b,np.array(meshed_a**2+meshed_b**2))


# Label the axes
ax.set_xlabel('X axis ------>')
ax.set_ylabel('Y axis ------>')
ax.set_zlabel('Z axis ------>')

# Display the surface plot
plt.show()

"""**Q:** How many plots can be seen in the output? Is there a relationship between the two equations?

**A:** There are two plots that can be seen. Yes, there is relationship between the two equations.

The two equations are only equal if a=0 and b=0 otherwise,

Equation 1: is the sum of a and b and then squared.

Equation 2: is the sum of squares of a and b.

Therefore, there are two surface plots seems to start at 0 and then separate.

**Hint:** You can refer the steps given in Activity 1 for performing this activity.

---

### Submitting the Project

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project77**) of the notebook will get copied.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project77** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""