# -*- coding: utf-8 -*-
"""Project 52

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QBu67HHqzgMpn_XNhAbYL5aqij0cZWcy

### Instructions

---

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

 1. Python Lists

 2. Python Dictionary

 3. Classes and Objects

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

    https://colab.research.google.com/drive/1ES6E4FS0TLyQ4wr8tRfEfwhvIwhKR1d1

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project52** format.

4. Now, write your code in the prescribed code cells.

---

### Problem Statement

In this project, create an interactive Library application using the concept of **Object Oriented Programming**.

Ask the user to enter a number from 1, 2, 3, 4, or 9. These numbers indicate the following options:

  - **1: Display books** $\Longrightarrow$ This option displays all books in the library.

  - **2: Lend a book** $\Longrightarrow$ This option allows the user to lend a book to another user.

  - **3: Add a book** $\Longrightarrow$ This option enables the user to add a new book to the library.

  - **4: Collect a book** $\Longrightarrow$ This option will collect the book back from the user.

  - **9: Quit** $\Longrightarrow$ This option will allow the user to quit the application.

---

### List of Activities

**Activity 1:** Create a `LibraryAdmin` class.

**Activity 2:** Create the following four functions inside the `LibraryAdmin` class:

 - `display_book()`: To display all the books.

 - `lend_book()`: To lend a book.

 - `add_book()`: To add a new book.

 - `collect_book()`: To collect a book back.  

**Activity 3:** Create an object of `LibraryAdmin` class.

**Activity 4:** Call the functions.

---

#### Activity 1: Create a `LibraryAdmin` Class

Create a class `LibraryAdmin`. Add a constructor (`__init()__` function) to the class. This constructor must initialise the following variables:

-  `list_books`: A list to store the list of books. Initialise this list with the values passed whenever a new object of `LibraryAdmin` class is created.
-  `borrowers_dict`: A dictionary to keep track of books lent to another user. Keep this dictionary empty.
"""

#  Create class LibraryAdmin and add constructor
class LibraryAdmin:
    def __init__(self,list_books = None,borrowers_dict = None):
        self.list_books = []
        self.borrowers_dict = {}

"""---

#### Activity 2: Add Functions

Add the following four functions inside the `LibraryAdmin` class:

- **The `display_books()` function**: Display all the books stored in the `list_books` list using `for` loop.

- **The `lend_book()` function**: This function takes two parameters; `book` and `borrower`. The `book` parameter holds the name of the book and the `borrower` parameter holds the name of the user to whom the book is to be lent.

  Inside this function, check whether the `book` is already present in the `borrowers_dict` dictionary or not.

  * If the `book` is not in `borrowers_dict{}`, update this dictionary using `update()` function. Pass the name of the book i.e. `book` variable as key and name of the user i.e. `borrower` variable as its `value` to the `update()` function.

  * If the `book` exists in `borrowers_dict{}`, this means that this book is already issued by another user. Thus, display the message "Sorry, this book is already issued".

- **The `add_book()` function**: This function takes a parameter `book` which holds the name of the book to be added to the library. Use the `append()` function to add the `book` to the `list_books` list. Also, display a message "Book has been successfully added in the Library".

- **The `collect_book()` function**: This function takes a parameter `book` which holds the name of the book to be removed from the `borrowers_dict` dictionary. Use the `pop()` function of the Python dictionary to remove the `book` from the `borrowers_dict` dictionary. Also, display a message "Book is successfully removed from the Library".

**Note:** Do not forget to keep `self` keyword as the first argument or parameter in all the class functions.
"""

# Create Functions inside 'Library' class.
class LibraryAdmin:
  def __init__(self,list_books,borrowers_dict=None):
    self.list_books = list_books
    self.borrowers_dict= {}
  def display_books(self):
    for books in self.list_books:
      print(books)
  def lend_book(self,book,borrower):
    if book not in self.borrowers_dict.keys():
      self.borrowers_dict.update({book:borrower})
      print("you have issued a book",book,"for the user",borrower)
    else:
      print("Sorry,this book is already issued")
  def add_book(self,book):

    self.list_books.append(book)
    print("Book has been successfully added in the Library")
  def collect_book(self,book):
    self.borrowers_dict.pop(book)
    print("Book is successfully removed from the Library")

"""---

#### Activity 3: Create an Object of `LibraryAdmin`

Create an object of `LibraryAdmin` class and pass a list as a parameter. This list consists of names of books that initially exist in your library.
"""

# Create an object of Library class and pass a list of books as a parameter
library_store = LibraryAdmin(["mathematics",
                              "informattion technology",
                              "chemistry",
                              "physics",
                              "python programming",
                              "hindi",
                              "english",
                              "social science",
                              "science"])
library_store

"""---

#### Activity 4: Call the Functions

Create an infinite `while` loop. Inside this `while` loop perform the following tasks:
1. Display the following list of choices:

```
Enter :
        1 to DISPLAY books
        2 to LEND a book
        3 to ADD a book
        4 to COLLECT a book
        9 to QUIT the application
```

2. Take user input and store it in a variable `user_choice`. Check whether the user entered any input other than 1, 2, 3, 4, or 9. If yes, then display a message "Please enter a valid option" and keep on asking for user input unless the user enters a valid choice.

3. Now using the `if-elif-else` statement, check user input and call the corresponding functions using the object of the `LibraryAdmin` class.
 - If `user_choice==1`, call the `display_books()` function
 - If `user_choice==2`, ask the user to enter the name of the book which is to be lent and the name of the borrower and pass them as parameters to the `lend_book()` function.
 - If `user_choice==3`, ask the user to enter the name of the book which is to be added and pass this as a parameter to the `add_book()` function.
 - If `user_choice==4`, ask the user to enter the name of the book which is to be collected back and pass this as a parameter to the `collect_book()` function.
 - If `user_choice==9`, break the infinite while loop using the `break` statement.


**Note:** Call all the four functions using the object of `LibraryAdmin` class only.
"""

# Call the functions
while True:
    print("""Enter :
        1 to DISPLAY books
        2 to LEND a book
        3 to ADD a book
        4 to COLLECT a book
        9 to QUIT the application""")
    user_choice = input(" Enter a number from above statements : ")

    while user_choice not in ['1','2','3','4','9']:
        print("Please enter a valid option")
        print("""Enter :
        1 to DISPLAY books
        2 to LEND a book
        3 to ADD a book
        4 to COLLECT a book
        9 to QUIT the application""")
        user_choice = input(" Enter a number : ")
    if user_choice == '1' :
        print("Welcome to our library store " ,'\n',
               "Please select any book from our libray store book  ")
        library_store.display_books()

    elif user_choice == '2' :
        book = input(" Please enter the name of the book : ")
        borrower = input(" Please enter the name of borrower : ")
        library_store.lend_book(book,borrower)

    elif user_choice == '3' :
        new_book = input(" Enter the name of the book to add in library : ")
        library_store.add_book(new_book)

    elif user_choice == '4' :
        remove_book = input(" Enter the name of the book to be collected : ")
        library_store.collect_book(remove_book)

    elif user_choice == '9' :
        print(" Thanks for visiting  our library store", '\n',
                "Try to come next time  to read new books !")
        break

"""---

### Submitting the Project:

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project52**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project52** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>
"""