# -*- coding: utf-8 -*-
"""project 98.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tSiSLpNpjjabtw_pMA-KveIR99BXytXG

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the lesson:

  Detect Credit Card Defaulters - Pivot Tables & Subplots

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

   https://colab.research.google.com/drive/1awgFNs0X--xyH6xHHv3_UknFfpC83_Ql

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project98** format.

4. Now, write your code in the prescribed code cells.

---

#### Context

A **gratuity** (normally called a **tip**) is a sum of money customarily given by a client or customer to certain service sector workers for the service they have performed, in addition to the basic price of the service.

Food servers’ tips in restaurants may be influenced by many
factors, including the nature of the restaurant, the size of the party, and table
locations in the restaurant. Restaurant managers need to know which factors
matter when they assign tables to food servers.

---

#### Problem Statement

In this project, you are going to create  pivot tables and subplots to summarise a given data.

---

### Dataset Description

This dataset contains the data of the total bill and tips given in a restaurant.

|Field|Description|
|---:|:---|
|total_bill|Total bill amount (in dollars)|
|tip|Tips are given (in dollars)|
|sex|Gender of the person|
|smoker|Wheather the person is a smoker or non-smoker|
|day|Day of their visit to the restaurant|
|time|Whether the person visited the restaurant for either lunch or dinner|
|size|Number of people having their food together|

**Dataset Credits:** The dataset is available through the Python package `seaborn`.

---

### List of Activities

**Activity 1:** Pivot Table
  
**Activity 2:** Subplots

---

#### Activity 1: Pivot Table


Import the necessary Python modules, read the data from a csv file to create a Pandas DataFrame and go through the necessary data-cleaning process (if required).

Load the **tips.csv** dataset using `load_dataset()` function of the `seaborn` package as follows:

`sns.load_dataset('tips')`
"""

# Import the modules, read the dataset and create a Pandas DataFrame.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# Load tips dataset from online repository using 'seaborn' module.
df = sns.load_dataset('tips')
# Print the first five records
df.head()

"""Print the concise summary of the tips dataset to check if there exist any missing values:"""

# Get the total number of rows and columns, data types of columns and missing values (if exist) in the dataset.
print("Shape of dataframe :",df.shape)
print("-----"*10)
print("Datatypes of dataframe :",df.dtypes)
print("-----"*10)
print(df.isnull().sum())

"""
Display the median value of the `tip` column values and group them by `sex` and `time` columns using pivot table."""

# Display the median value of the 'tip' column values and group them by 'sex' and 'time' columns.
pivot_table_tip = pd.pivot_table(data=df,values=['tip'],index=['sex','time'],aggfunc='median')
pivot_table_tip

"""Display the total value of the `total_bill` column values and group them by `day` and `size` columns using pivot table."""

# Display the total value of the 'total_bill' column values and group them by 'day' and 'size' columns.
pivot_table_total_bill = pd.pivot_table(data=df,values=['total_bill'],index=['day','size'],aggfunc='sum')
pivot_table_total_bill

"""**Q**: Which day has the maximum total bill amount?

**A**: Saturday has the maximum total bill amount.

**Q**: What is the size of the people with the maximum total bill amount?

**A**: Size 2 of the people have the maximum total bill amount.

After this activity, there would be two pivot tables, one which displays the median tips value and the other one which displays the total bill amount.

---

#### Activity 2: Subplots

1. Create count plots displaying the `gender` grouped by the `day`, `smoker`, and `time` together through just one figure.
"""

# Create count plots displaying 'gender' grouped by 'day', 'size', and 'time' in just one figure.
fig,axis = plt.subplots(nrows=1,ncols=3,figsize=(14,5),sharey=True)
sns.countplot(x='day',hue='sex',data=df,ax = axis[0])
sns.countplot(x='size',hue='sex',data=df,ax = axis[1])
sns.countplot(x='time',hue='sex',data=df,ax = axis[2])
plt.show()

"""2. Create box plots displaying `total_bill` amount and `tip` grouped by `day`, `smoker`, and `time` in just one figure.

  
"""

# Create box plots displaying the 'total_bill' amount and 'tip' grouped by 'day', 'smoker', and 'time' in just one figure.
fig1,axis1=plt.subplots(nrows=2,ncols=3,figsize=(14,5),sharey=False)

# For 'total_bill' column.
sns.boxplot(x='day',y='total_bill',hue='sex',data=df,ax=axis1[0,0])
sns.boxplot(x='smoker',y='total_bill',hue='sex',data=df,ax=axis1[0,1])
sns.boxplot(x='time',y='total_bill',hue='sex',data=df,ax=axis1[0,2])

# For 'tip' column.
sns.boxplot(x='day',y='tip',hue='sex',data=df,ax=axis1[1,0])
sns.boxplot(x='smoker',y='tip',hue='sex',data=df,ax=axis1[1,1])
sns.boxplot(x='time',y='tip',hue='sex',data=df,ax=axis1[1,2])
plt.show()

"""**Hint:** To get an axis at second row and third column from a grid of, say 3 rows and 5 columns figure, use `axis[1, 2]`.

After this activity, the user must be able to view multiple plots in just one figure using the concept of subplots.

---

### Submitting the Project:

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project98**) of the notebook will get copied.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project98** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""