# -*- coding: utf-8 -*-
"""Project 58

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y5xDGmDaE8Xmo3BAZKPRqgTDCVt3PPEf

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

 1. Scatter and Line Plots

 2. Boxplot

 3. Pie Chart and Bell Curve

 4. Simple Linear Regression

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

  https://colab.research.google.com/drive/1cmuoUGEIdAyM4uLGJVopyy_TlRLMUved

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project58** format.

4. Now, write your code in the prescribed code cells.

---

### Activities

#### Activity 1: Create Pandas DataFrame

Create a Pandas DataFrame for the **Weight-Height** dataset using the below link. This dataset has 10,000 rows and provides the weight, height and gender of the person.

**Dataset Link:** https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/weight-height/weight-height.csv

Also, print the first five rows of the dataset. Check for null values and treat them accordingly.

---
"""

# Import modules
# Dataset Link: 'https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/weight-height/weight-height.csv'
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/weight-height/weight-height.csv")
df.head()

# Check if there are any null values. If any column has null values, treat them accordingly
df.isnull().sum()

# Get the descriptive statistics summary of the DataFrame
df.describe()

"""---

#### Activity 2: Create Pie Chart

Find out whether the dataset is balanced i.e., whether the dataset has an equal number of Male and Female. For this, create a pie chart with labels.
"""

# Check if the dataset is balanced or not using pie chart for 'Gender'
list1 = ["Male","Female"]
list2 = [0.1,.1]
gender = (df["Gender"].value_counts())*100/df.shape[0]
plt.figure(figsize =(20,5),dpi = 100)
plt.pie(gender,labels = list1,wedgeprops = {"edgecolor": "blue"},autopct ='%3.00f%%',explode =list2,shadow =True)
plt.show()
print(gender)

"""**Q:** Is there an equal distribution of males and females in the above dataset?

**A:** Yes

---

#### Activity 3: Boxplot for Heights and Weights

Create boxplots to show the distribution of weight and height in males and females.
"""

# Create a boxplot for gender-wise variation in heights.
plt.figure(figsize= (20,5))
sns.boxplot(x = "Height",y = "Gender",data = df, hue="Gender",color = 'teal')
plt.xlabel("Height ----->")
plt.ylabel("Weight ----->")
plt.show()

# Create a boxplot for gender-wise variation in weights.
plt.figure(figsize= (20,5))
sns.boxplot(x = "Weight",y = "Gender",data = df, hue="Gender",color = 'teal')
plt.show()

"""**Q:** What can be concluded from the above boxplot, who is taller and heavier in weight, Male or Female?

**A:** We concluded that male are taller and heavier in weight than female.

----

#### Activity 4: Create Scatter Plot and Regression Plot

Create a scatter plot and a regression plot to identify if there exists any relationship between height and weight of a person.
"""

# Create a scatter plot with height on X-axis and weight on Y-axis
plt.figure(figsize= (20,5))
sns.scatterplot(x = "Height",y = "Weight" ,data = df, hue = "Gender",color ='teal')
plt.xlabel("Height ------->")
plt.ylabel("Weight ------->")
plt.show()

# Create a regression plot for height and weight
plt.figure(figsize = (20,5))
sns.regplot(df["Height"],df["Weight"],color = 'teal')
plt.xlabel("Height ------>")
plt.ylabel("Weight ------>")
plt.show()

"""**Q:** Is there exists a positive linear relationship between heights and weights of individuals?

**A:** Yes,there exists a positive linear relationship between heights and weights of individuals.

---

### Submitting the Project:

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project58**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project58** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>
"""