# -*- coding: utf-8 -*-
"""Project 92.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCHsLuoNCNsbY3EyOC-WK3TUt8LwjMBE

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the lesson:

  Streamlit Framework I

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

   https://colab.research.google.com/drive/1ENKsDawDjF-ylErt8kNS6vesj05bXxsV

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project92** format.

4. Now, write your code in the prescribed code cells.

---

#### Problem Statement

In this project, you are going to create Python web apps using the Streamlit framework.

---

####Context
Equated Monthly Installment is the fixed amount of money the borrower pays the lender on a specific date for a specific period.

EMI calculator is a tool that calculates how much amount you have to pay monthly towards your loan. The EMI calculator can be customised to calculate home loan, personal loan, vehicle loan, etc.

The formula used to calculate fixed monthly repayment is based on the annuity formula and is represented as:

$$\text{Fixed monthly repayment} = p \times r \times \frac{(1 + r)^n}{(1+r)^n -1}$$

Where,

- $p$: The principal outstanding loan amount.

- $r$: The interest rate per month.

- $n$: The tenure of the loan in months.

For every type loan, the calculations are different based on a lot of financial factors. But **Morgage Formula** is always used as a base formula.

The formula above is the first part of the **Morgage Formula**. The second part is used to find Outstanding Loan Balance after certain months.

The formula for calculating the Outstanding Loan Balance after $m$ months is given as:

$$\text{Outstanding Loan Balance} = p \times \frac{(1 + r)^n - (1 + r)^m}{(1+r)^n -1}$$

Where,

$m$: The number of months after which the Outstanding Loan Balance is calculated.

----

### List of Activities

**Activity 1:** Create an EMI Calculator App.
  
**Activity 2:**  Improvised EMI Calculator App.

---

####Activity 1: Create an EMI Calculator App

In this activity, you have to create a Streamlit app to calculate the EMI based on the formula given above. The user can interactively choose the principal loan amount, tenure, and rate of interest using the Streamlit sliders. The range for these inputs is as given below:


|Input|Description|Range|
|-|-|-|
|principal|Principal Loan Amount|1000 - 1000000|
|tenure|Loan period (in years)|1 - 30|
|roi|Rate of Interest (in % per annum)|1 - 15|

Perform the following tasks in **Sublime editor** and run your code using command prompt or terminal. Once you get the desired output, write the code in the code section given below:

1. Import `streamlit` module.

2. Create a function `calculate_emi()` that accepts three inputs `(p, n, r)` and calculates the emi based on the formula given below. Print the calculated emi (rounded off to 3 decimal places).
    
$$ emi = p \times \frac{r}{100} \times \frac{(1 + \frac{r}{100})^n}{[(1+\frac{r}{100})^n -1]}$$

  


3. Add the title to the app.

4. Add three sliders for selecting the values for the three inputs. Store the current value of these slider widgets in three different variables, `principal`, `tenure`, and `roi`.

5. Obtain the tenure of a loan in months i.e `n` and monthly rate of interest `r`.

6. Add a button to calculate EMI. If the user clicks on this button, call the function `calculate_emi()` and pass the `principal`, `n`, and `r` variables to this function.
  

**Note:** In the formula, The rate of interest `r` is in the percentage, hence, it the value is divided by `100` to deduce the actual `r`.
"""

num = 45
num1 = 12.00
product = num*num1
print(round(product,3))

# Write the code for creating the EMI calculator app
import streamlit as st
def calculate_emi(p,n,r):
    emi = p* r/100 *(1+r/100)**n/(1+r/100)**n-1
    emi = round(emi,3)
    return emi
principal = st.slider("Principal",1000,50000)
tenure = st.slider("Tenure",1,12)
roi = st.slider("Rate",1,15)
n = 12
r = float(roi / 12)
if st.button("Calculate"):
    calculated_emi = calculate_emi(principal,n,r)
    st.write("Principal amount borrowed is",principal,"for tenure of intrest by year is  ",n,"by the rate of",r,"percent per annum then the emi will be",calculated_emi)

"""**Hint:** You have to multiply `tenure` by `12` to calculate `n` and divide `roi` by `12` to calculate `r`. This is because the value of `n` and `r` used in the formula is for per month and the `tenure` is given in years and the `roi` is given for per annum (12 months).

**Q:** What will be the EMI if the Principal Amount borrowed is `50000` for the tenure of `2` years with Rate of interes as `5.05` percent per annum?

**A:** If the Principal Amount borrowed is `50000` for the tenure of `2` years with Rate of interes as `5.05` percent per annum is 209.417 .

----

####Activity 2: Improvised EMI Calculator App

In this activity, you will improvise the above EMI calculator app by adding the feature. This feature will allow the user to calculate the **Outstanding Loan Balance** in addition to Monthly EMI. For the improvised app, there will be an additional input:


|Input|Description|Range|
|-|-|-|
|m|Period after which the Outstanding Loan Balance is calculated (in months)|1 - $(tenure \times 12)$|

Perform the following tasks in **Sublime editor** and run your code using command prompt or terminal. Once you get the desired output, write the code in the code section given below:

1. Import `streamlit` module.

2. Create a function `calculate_emi()` as created in  **Activity 1**.

3. Create another function `calculate_outstanding_balance()` that accepts four inputs `(p, n, r, m)` and calculates the outstanding loan balance based on the formula given below. Print the calculated outstanding balance (rounded off to 3 decimal places).

$$balance = \frac{[p * (1 + \frac{r}{100})^n - (1 + \frac{r}{100})^m) ]}{[(1 + \frac{r}{100})^n - 1]}$$

4.  Add the title to the app.

5. Add four sliders for selecting the values for the input. Store the current value of these slider widgets in four different variables.

6. Obtain the tenure of a loan in months i.e `n` and monthly rate of interest `r`.

7. Add two buttons to calculate EMI and Outstanding Loan Balance.
  - Create a condition such that if the user clicks on the first button, call the function to calculate EMI.
  - Create a condition such that if the user clicks on the second button, call the function to calculate Outstanding Loan Balance.
"""

# Write the code for creating the Improvised EMI calculator app
import streamlit as st

def calculate_emi(p,n,r) :
    emi = p * (r / 100) * (((1 + (r/100))** n) / (((1 + r/100) ** n) - 1))
    return round(emi, 3)

def calculate_outstanding_emi(p, n, r, m) :
    numerator = (p * ((1 + r/100)**n) - (1 + r/100) **m)
    denominator = ((1 + r/100) **n - 1)
    balance = numerator/denominator
    return round(balance, 3)

st.title("Improvised EMI Calculator App")

principal = st.slider('Principal', 10000, 50000)
tenure = st.slider('Tenure', 1, 30)
roi = st.slider('Rate of interest', 1.00, 15.00)
m = st.slider('Period after which the Outstanding Loan Balance is calculated(in months)',1, (tenure * 12))

n = tenure * 12
r = roi / 12

if st.button('Calculate EMI'):
    calculated_emi = calculate_emi(principal, n, r)
    st.write("Principal amount borrowed is",principal,"for tenure of intrest by months is  ",n,"by the rate of",r,"percent per annum then the emi will be",calculated_emi)


if st.button('Calculate Outstanding Loan Balance')  :
    loan = calculate_outstanding_emi(principal, n, r, m)
    st.write('Outstanding Balance Amount is ', loan)

"""**Hint:** To create two buttons, save them in different variables and use the variables in `if` conditions.

**Q:** What will be the Outstanding Balance Amount after `4` months if the Principal Amount borrowed is `50000` for the tenure of `2` years with Rate of interes as `5.05` percent per annum?

**A:** The Outstanding Balance Amount after `4` months if the Principal Amount borrowed is `50000` for the tenure of `2` years with Rate of interes as `5.05` percent per annum is `521500.732` .

---

### Submitting the Project:

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project92**) of the notebook will get copied.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project92** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""