# -*- coding: utf-8 -*-
"""Project 54.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TYiDfNPF00E5jEagEdV8PR02a3x9b1Xs

### Instructions

---

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

 1. Classes and Objects

 2. Inheritance

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

    https://colab.research.google.com/drive/1IYo2c9R9XgSEY2Ik86h_spkH44p8Daf7

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project54** format.

4. Now, write your code in the prescribed code cells.

---

### Problem Statement


From the stone age till the electronic age we have used numerous ways of distance communication, one of them being **Mail Service**.

Let's say you are building a Mailing Service Application which will allow you to send mails. These mails can be emails, physical mails, fax, etc.

Every mail will have four things in common:
1. Sender’s Address
2. Receiver’s Address
3. Subject
4. Message

Every type of mail possess some unique attributes like:
* In a courier, you need the weight of the parcel.
* In an email, you may have an Attachment.

Let's build this application using Inheritance.

---

### List of Activities

**Activity 1:** Create a parent class `Mail`.

  
**Activity 2:** Create an object of the class `Mail`

**Activity 3:** Create a child class `Post` which inherits from the parent class `Mail`.

**Activity 4:** Create a child class `Email ` which inherits from its parent class `Mail`.

---

#### Activity 1: Create Parent Class `Mail`


1. Create a class `Mail`. The constructor of this class must initialise the following variables:

 - `sender_add`: Address of the sender.

 - `receiver_add`: Address of the receiver.

 - `subject`: Context of the mail.

 - `message`: Message which needs to be communicated.


2. Create a `__repr__()` function to print the above variables in a format as given in the example below:

```
To:     	Prime Minister
From:   	State Minister
Subject:	Health Policy
Message:	This is regarding the Health Policy 2020
```
"""

#  Create class 'Mail'. Add constructor
class Mail:
    def __init__(self,sender_add,receiver_add,subject,message):
        self.sender_add = sender_add
        self.receiver_add = receiver_add
        self.subject = subject
        self.message = message

  # Create a __repr__ to return the properties of a mail
    def __repr__(self):
        return ('To: ',self.sender_add,
                'From: ',self.receiver_add,
                'Subject: ',self.subject,
                'Message: ',self.message )

"""---

#### Activity 2: Create an Object of `Mail` Class

Create an object of `Mail` class and display the attributes  using the object
"""

# Create an object of 'Mail' class and print its properties
mail = Mail("Prime Minister","State Minister","Health Policy ","This is regarding the Health Policy 2020")
print(mail.sender_add)
print(mail.receiver_add)
print(mail.subject)
print(mail.message)

"""---

#### Activity 3: Create a Child Class `Post`


1. Create a child class `Post` which inherits from the parent class `Mail`. In addition to the properties of the parent class, the constructor of this class must initialise the following properties:

  - `mode_of_transit`: Transport method. It can have only one of the three values:

     * Waterways
     * Roadways
     * Airways

  - `delivery_time`: Time taken to deliver the post. It is initially set to `None`.

  
2. Create the following function inside the child class:

  -  `calculate_delivery_time()`: This function determines the `delivery_time` based on the following conditions:

     * If `mode_of_transit` is Airways, then `delivery_time` will be "In 5 working days".
     * If `mode_of_transit` is Roadways, then `delivery_time` will be "In 15 working days".
     * If `mode_of_transit` is Waterways, then `delivery_time` will be "In 10-15 working days".

      .

  - Create a `__repr__()` function to print the message in a format as given in the example below:
```
To:     	      Prime Minister
From:   	      State Minister
Subject:	      Health Policy
Message:	      This is regarding the Health Policy 2020
Transit Mode: 	Airways
Delivery Time: 	In 5 working days
```
3. Create an object of this class and pass the desired values as parameters to its constructor.
"""

# Create child class 'Post' of the parent class 'Mail' and create the object of the child class and determine the delivery time
class Post(Mail):
    def __init__(self,sender_add,receiver_add,subject,message,mode_of_transit,delivery_time= None):
        Mail.__init__(self,sender_add,receiver_add,subject,message)
        self.mode_of_transit = mode_of_transit
        self.delivery_time = []
    def __repr__(self):
        return (f'To: {self.sender_add} \n From: {self.receiver_add} \n Subject: {self.subject} \n Message:{self.message} \n Transit Mode: {self.mode_of_transit} \n Delivery Time:{self.delivery_time}' )


    def calculate_delivery_time(self):
        if self.mode_of_transit == "Airways":
            self.delivery_time = "In 5 working days"
        elif self.mode_of_transit == "Roadways":

            self.delivery_time = "In 15 working days"
        elif self.mode_of_transit == "waterways":
            self.delivery_time = "In 10-15 working days"

mps = Post('Prime Minister',
            'State Minister',
            'Health Policy',
            'This is regarding the Health Policy 2022',
            'Airways')
mps.calculate_delivery_time()
mps

"""---

#### Activity 4: Create a Child Class `Email`


1. Create a child class `Email` which inherits from the parent class `Mail`. In addition to the properties of the parent class, the constructor of this class must initialise the following properties:

  - `status`: The status of the sent email. It can have any one of the following values:
  
    * Draft
    * Sent



  
2. Create the following functions inside the child class:

  - `update_message()`: A function which will update the `message` variable. If the `status` of the email is `Draft`, then update the `message` variable with the new message passed as a parameter to this function else print **"Message already sent. Update not possible"**

 2. Create a `__repr__()` function to print the message in a format as given in the example below:
```
To:     	Prime Minister
From:   	State Minister
Subject:	Health Policy
Message:	Policy 2020
Status: 	Draft
```
3. Create an object of this class and pass the desired values as parameters to its constructor.
"""

# Create child class 'Email' of the parent class 'Mail'. Create the object of the child class and update an existing draft.
class Email(Mail):
    def __init__(self,sender_add,receiver_add,subject,message,status):
        super().__init__(sender_add,receiver_add,subject,message)
        self.status = status
    def update_message(self,draft):
        if self.status == "Draft":
            self.message = draft
        else:
            print("Message already sent.Update not possible")
    def __repr__(self):
        return (f'To:{self.sender_add} \n From:{self.receiver_add} \n Subject:{self.subject} \n Message:{self.message} \n Status:{self.status}')
e_mail = Email(" Prime Minister"," State Minister"," Health Policy "," Policy 2022 Covoid-19 & Omicron "," Draft ")
e_mail.update_message("message has been saved")

e_mail

"""---

### Submitting the Project:

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project54**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project54** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""