# -*- coding: utf-8 -*-
"""Project 72

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ap9rSzIfvu8nIyA2-gdG1Twou2mOkw3W

### Instructions

---

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

 1. Deploying A Prediction Model
 2. Model Evaluation
 3. Logistic Regression - Univariate I

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

   https://colab.research.google.com/drive/1iHDryTxcrnUlwK69EN0OOfXDzTdTEkEK

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project72** format.

4. Now, write your code in the prescribed code cells.

---

### Problem Statement

Nowadays, social media advertising is one of the popular forms of  advertising. Advertisers can utilise user's demographic information and target their ads accordingly.

Implement Random Forest Classification and Logistic Regression to determine whether a user will purchase a particular product displayed on a social network ad or not.  Compare the accuracy of both the classification algorithms.

---

### List of Activities

**Activity 1:** Analysing the Dataset

**Activity 2:** Train-Test Split

**Activity 3:** Random Forest Classification - Model Training

**Activity 4:** Random Forest Classification - Model Prediction and Evaluation

**Activity 5:** Logistic Regression - Model Training

**Activity 6:** Logistic Regression - Model Prediction and Evaluation

**Activity 7:** Comparision and Conclusion

---

#### Activity 1:  Analysing the Dataset

- Create a Pandas DataFrame for **Social Network** dataset using the below link. This dataset consists of following columns:

|Field|Description|
|---:|:---|
|UserID|Unique ID|
|Gender|Male or Female|
|Age|Age of a person|
|EstimatedSalary|Salary of a person|
|Purchased|‘0’ or ‘1’. ‘0’ means not purchased and ‘1’ means purchased.|


  **Dataset Link:** https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/social-network-ads.csv

- Print the first five rows of the dataset. Check for null values and treat them accordingly (if any).

- Create a heatmap to identify the relationship between the independent attributes and dependent attribute `Purchased`.
"""

# Import modules
import pandas as pd
import numpy as np
import seaborn as sns
import statsmodels.api as sample_data
from scipy.stats import norm
import matplotlib.pyplot as plt
# Load the dataset
# Dataset Link: 'https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/social-network-ads.csv'
df = pd.read_csv('https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/social-network-ads.csv')
# Print the first five rows of the dataframe
df.head()

# Print the dataset information
print(df.info())
print("----"*10)
print("Checking Null values",' \n',df.isnull().sum())

"""**Q:** Are there any missing values?

**A:** No
"""

# Create a heatmap to identify the relation between attributes
plt.figure(figsize=(20,5),dpi = 96)
sns.heatmap(df.corr(),annot = True)
plt.show()

"""**Q:** Which attribute(s) has the strongest relationship with the `Purchased` feature?

**A:** `Age` attribute(s) has the strongest relationship with the `Purchased` feature.

---

#### Activity 2: Train-Test Split

We have to determine the effect of `Age` on purchase of the products. Thus, `Age` is the feature variable and `Purchased` is the target variable.

- Split the dataset into training set and test set such that the training set contains 70% of the instances and the remaining instances will become the test set.

- Reshape the feature and the target variable arrays into two-dimensional arrays by using `reshape(-1, 1)` function of `numpy` module.
"""

# Split the DataFrame into the train and test sets.
from sklearn.model_selection import train_test_split
X = df['Age']
y = df['Purchased']

# Split the DataFrame into the train and test sets such that test set has 30% of the values.
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.33, random_state  = 42)

# Reshape to 2-dimensional array.
X_train = np.array(X_train).reshape(-1,1)
X_test = np.array(X_test).reshape(-1,1)
y_train = np.array(y_train).reshape(-1,1)
y_test = np.array(y_test).reshape(-1,1)

"""----

#### Activity 3: Random Forest Classification - Model Training

Implement Random Forest Classification using `sklearn` module in the following way:

1. Deploy the model by importing the `RandomForestClassifier` class and create an object of this class.
2. Call the `fit()` function using the Random Forest Classifier object and print score using `score()` function using the object created.
"""

# Import the required modules from the 'sklearn.ensemble' and 'sklearn.metrics' libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix

# Train the Random Forest Classifier
rf_clf = RandomForestClassifier(n_jobs = -1 , n_estimators = 100)
rf_clf.fit(X_train,y_train)
rf_clf.score(X_train,y_train)

"""-----

#### Activity 4: Random Forest Classification - Model Prediction and Evaluation

Predict the values for both training and test sets by calling the `predict()` function on the Random Forest Classifier object.

Also, compute confusion matrix and classification report values to evaluate the accuracy of your model.
"""

# Make predictions on the test dataset by using the 'predict()' function.
rfc_y_pred = rf_clf.predict(X_test)
rfc_y_pred

# Check the count of records classified under each label
pd.Series(rfc_y_pred).value_counts()

# Display the results of 'confusion_matrix'
confusion_matrix(y_test,rfc_y_pred)

# Display the precision, recall and f1-score values.
print(classification_report(y_test,rfc_y_pred))

"""**Q** Write the count of f1-score of both labels?

**A:**  0.80 and 0.78 are f1-score of both labels.

----

#### Activity 5: Logistic Regression - Model Training

Implement Logistic Regression Classification using `sklearn` module in the following way:

1. Deploy the model by importing the `LogisticRegression` class and create an object of this class.
2. Call the `fit()` function on the Logistic Regression object and print score using `score()` function using the object created.
"""

# Deploy the 'LogisticRegression' model using the 'fit()' function.
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(n_jobs = -1)
log_reg.fit(X_train,y_train)
log_reg.score(X_train,y_train)

"""----

#### Activity 6: Logistic Regression - Model Prediction and Evaluation

Predict the values for both training and test sets by calling the `predict()` function on the Logistic Regression object.

Also, compute the confusion matrix and classification report values to evaluate the accuracy of your model.
"""

# Make predictions on the test dataset by using the 'predict()' function.
log_y_pred = log_reg.predict( X_test )
log_y_pred

# Display the results of confusion_matrix
confusion_matrix(y_test,log_y_pred)

# Display the results of classification_report
print(classification_report(y_test,log_y_pred))

"""**Q** Write the count of f1-score of both labels?

**A:** 0.91 and 0.83 f1- score of the labels.

-----

#### Activity 7: Comparision and Conclusion

Test both the models to predict labels using same random values of `Age` attribute.
"""

# Predict labels with same random values from dataset
# Using Random Forest Classifier
print(rf_clf.predict(np.array(df['Age'][25]).reshape(-1,1)))
print(rf_clf.predict(np.array(df['Age'][245]).reshape(-1,1)))
print("-" * 20)

# Using Logistic Regression
print(log_reg.predict(np.array(df['Age'][25]).reshape(-1,1)))
print(log_reg.predict(np.array(df['Age'][245]).reshape(-1,1)))

"""**Q** Which model is better and why?

**A:** Since model of Logistic regression is good as it satisfies both as `shape` of 1.

------

### Submitting the Project:

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project72**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project72** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""