# -*- coding: utf-8 -*-
"""Project 56.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Pi49Hw7GcLeNOIKmg5KX-cY5ZFo_rS4

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

 1. Classes and Objects

 2. Polymorphism I

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

    https://colab.research.google.com/drive/1Tms4FUViMTmiOaPPfqSww0HuGv_HRcor

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project56** format.

4. Now, write your code in the prescribed code cells.

---

#### Activity 1: Operator Overloading for `Rectangle`

Create a class `Rectangle` having two private instance variables `length` and `breadth`. Add getter and setter functions for both the private variables. Create a function to calculate the area of the rectangle:
$$\text{area of rectangle = length * breadth}$$

Create two `Rectangle` objects `rect1` and `rect2` and add both the objects by overloading the `+` operator as follows:
$$rect3 = rect1 + rect2$$

Adding the two `Rectangle` objects should give another `Rectangle` object `rect3` whose length is the sum of the lengths of the two `Rectangle` objects and whose breadth is the sum of the breadths of the two `Rectangle` objects.


Also, calculate the area of the `rect3` Rectangle object.

**Hint:** Overload the magic function `__add__()`
"""

#  Create a class 'Rectangle'. Add constructor to initialise variables
class Rectangle :

    def __init__(self,length,breadth):
        self.__length = length
        self.__breadth = breadth

    def get_length(self):
        return self.__length

    def get_breadth(self):
        return self.__breadth

    def set_length(self,new_length):
        self.__lenght = new_length

    def set_breadth(self,new_breadth):
        self.__breatdh = new_breadth

    def __add__(self,other):
        new_length = self.__length + other.__length
        new_breadth = self.__breadth + other.__breadth
        new = Rectangle(new_length,new_breadth)
        return new

    def get_area(self):
        return self.__length * self.__breadth

rect1 = Rectangle(4,6)
rect2 = Rectangle(5,10)
rect3 = rect1 + rect2
print('Length of rect1 =',rect1.get_length())
print('Length of rect2 =',rect2.get_length())
print('Length of rect1 + length of rect2 =',rect1.get_length() + rect2.get_length())
print('Equal to length of rect3 =',rect3.get_length())
print('-' * 50)
print('Breadth of rect1 =',rect1.get_breadth())
print('Breadth of rect2 =',rect2.get_breadth())
print('Breadth of rect1 + breadth of rect2 =',rect1.get_breadth() + rect2.get_breadth())
print('Equal to breadth of rect3 =',rect3.get_breadth())
print('-' * 50)
print('Area of rect1 in square unit =',rect1.get_area())
print('Area of rect2 in square unit =',rect2.get_area())
print('Area of rect3 in square unit =',rect3.get_area())

"""---

####Activity 2: Operator Overloading for `Circle`.



Create a class `Circle` having a private instance variable `radius` and getter and setter function for this variable. Create a function to calculate the area of the circle:
$$\text{area of circle} = \pi * radius^2$$

Create two `Circle` objects `circle1` and `circle2` and add both the objects by overloading the `+` operator as follows:
$$circle3 = circle1 + circle2$$

Adding the two `Circle` objects should give another `Circle` object `circle3` whose radius is the sum of the radii of the two `Circle` objects.Also, calculate the area of the `circle3` Circle object.

In addition to the `+` operator, overload the `>` (greater than) operator so that you can compare the two Circles to find out which one is bigger as follows:
$$circle1 > circle2$$

For this, compare the radii of the Circle objects and decide which is bigger.

**Hint:** Overload the magic functions `__add__()` and `__gt__()`.
"""

#  Create a class 'Rectangle'. Add constructor to initialise the variable and calculate area
import numpy as np
class Circle:

    def __init__(self,radius):
        self.__radius=radius

    def get_radius(self):
        return self.__radius

    def set_radius(self,new_radius):
        self.__new_radius=new_radius

    def __add__(self,other):
        new_radius = self.__radius + other.__radius
        new = Circle(new_radius)
        return new

    def __gt__(self,other):
        if self.__radius<other.__radius:
            return "first circle greater than the second circle."
        else:
            return "second circle is greater than the first circle."

    def  area(self):
        area = np.pi*self.__radius
        return area
circle1 = Circle(20)
circle2 = Circle(15)
circle3 = circle1 + circle2
print('Radius of circle1 =',circle1.get_radius())
print('Radius of circle2 =',circle2.get_radius())
print('Radius of circle1 + radius of circle2 =',circle1.get_radius() + circle2.get_radius())
print('Equal to radius of circle3 =',circle3.get_radius())
print('-'* 50)
print('Area of circle1 in square unit  =',circle1.area())
print('Area of circle2 in square unit =',circle2.area())
print('Area of circle3 in square unit =',circle3.area())

"""---

### Submitting the Project:

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project56**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project56** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>
"""