# -*- coding: utf-8 -*-
"""project 75

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-VPSALRaHMyQG8p_jo-SIJSQqsrP_2X

### Instructions

---

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the Logistic Regression - Likelihood Function lesson.

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

    https://colab.research.google.com/drive/1pRWyvWgRAsmi6t1-8wGHJK0ode4eMgrN

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project75** format.

4. Now, write your code in the prescribed code cells.

---

### List of Activities

**Activity 1:** Plot a graph with $y = \{\log_{10} x, \log_{10} 2x, \log_{10} 3x, \log_{10} 5x, \log_{10} 10x \}$

  
**Activity 2:**  Plot a graph with $y=\{\log_{1.1} x,\log_{2} x, \log_{3} x,\log_{5} x,\log_{10} x\}$

**Activity 3:**   Plot a graph with $y=\{\log_{10} x,x,x^2\}$


**Activity 4:** Plot a graph with $y=\{\log_e x,\log_e (x+4),\log_e x+4\}$

**Activity 5:** Plot a graph with $y=\{\log_e x,(\log_e (x))^2,\log_e (x^2)\}$

---

#### Activity 1:  Plot a Graph with $y = \{\log_{10} x, \log_{10} 2x, \log_{10} 3x, \log_{10} 5x, \log_{10} 10x \}$


1. Take list `x` and store number 1 to 99.

2. Calculate corresponding values for $y = \{\log_{10} x, \log_{10} 2x, \log_{10} 3x, \log_{10} 5x, \log_{10} 10x \}$
and store them in variables `y1`, `y2`,`y3`, `y4`, and `y5` respectively.

3. Plot the graph and make your observations.
"""

# Import required libraries.
import math
import numpy as np
import matplotlib.pyplot as plt


# Take input for x-axis.
X = [i for i in range(1,100)]
y1 = []
y2 = []
y3 = []
y4 = []
y5 = []
for i in X:
# Evaluate log(x) with base 10 for corresponding values of x.
    y1.append(math.log(i, 10))

# Evaluate log(2x) with base 10 for corresponding values of x.
    y2.append(math.log(2 * i, 10))

# Evaluate log(3x) with base 10 for corresponding values of x.
    y3.append(math.log(3 * i, 10))

# Evaluate log(5x) with base 10 for corresponding values of x.
    y4.append(math.log(5 * i, 10))

# Evaluate log(10x) with base 10 for corresponding values of x.
    y5.append(math.log(10 * i, 10))

# Plot the graphs
plt.figure(figsize = (16,5),dpi= 96)
plt.plot(X, y1, label = '$log_{10}x$')
plt.plot(X, y2, label = '$log_{10}2x$')
plt.plot(X, y3, label = '$log_{10}3x$')
plt.plot(X, y4, label = '$log_{10}5x$')
plt.plot(X, y5, label = '$log_{10}10x$')
# Label the x-axis
plt.xlabel('Base values ------> ')
# Label the y-axis
plt.ylabel('Log values  ------> ')
# Add a title to the graph
plt.title('Graph of y = {log10x,log102x,log103x,log105x,log1010x}')
# Show a legend on the plot
plt.legend()
# Function to show the plot
plt.show()

"""**Q:** What are your observations?

**A:** We can observe that when we multiply x with greater value, logarithmic function increases. Here as we go on multiply x with 2,3,5 and 10 we can see the curves in the graph increasing.

---

#### Activity 2: Plot a graph with $y=\{\log_{1.1} x,\log_2 x,\log_3 x,\log_5 x,\log_{10} x\}$

Calculate corresponding values for $y=\{\log_{1.1} x,\log_2 x,\log_3 x,\log_5 x,\log_{10} x\}$
and store them in variables `y1`, `y2`,`y3`, `y4`, and `y5` respectively.
"""

y1 = []
y2 = []
y3 = []
y4 = []
y5 = []
for i in X:
# Evaluate log(x) with base 1.1 for corresponding values of x.
    y1.append(math.log(i, 1.1))

# Evaluate log(x) with base 2 for corresponding values of x.
    y2.append(math.log(i, 2))

# Evaluate log(x) with base 3 for corresponding values of x.
    y3.append(math.log(i, 3))

# Evaluate log(x) with base 5 for corresponding values of x.
    y4.append(math.log(i, 5))

# Evaluate log(x) with base 10 for corresponding values of x.
    y5.append(math.log(i, 10))

# Plot the graphs
plt.figure(figsize =(16,5),dpi = 96)
plt.plot(X, y1, label = '$log_{1.1}x$')
plt.plot(X, y2, label = '$log_{2}2x$')
plt.plot(X, y3, label = '$log_{3}3x$')
plt.plot(X, y4, label = '$log_{5}5x$')
plt.plot(X, y5, label = '$log_{10}10x$')
# Label the x-axis
plt.xlabel("Base Values ------> ")
# Label the y-axis
plt.ylabel("Log Values -------> ")
# Add a title to the graph
plt.title("A graph with  y = {log1.1x,log2x,log3x,log5x,log10x}")
# Show a legend on the plot
plt.legend()
# Function to show the plot
plt.show()

"""**Q:** What are your observations?

**A:** From the above graph we can observe that as the base increases the logarithmic function decreases. Here from graph 1.1 to 10 the curves continues to decrease.

**Q:** Why do you think we used $1.1$ in the question rather than $1$ for comparison?

**A:** Logarithm of any number to the base 0 or 1 is undefined. So if we take 1.1 i.e. the float condition then the zero condition may not occur.

---

#### Activity 3: Plot a graph with $y=\{\log_e x,x,x^2\}$

Calculate corresponding values for $y=\{\log_e x,x,x^2\}$
and store them in variables `y1`, `y2`, and `y3`respectively.
"""

y1 = []
y2 = []
y3 = []
for i in X:

# Evaluate log(x) for corresponding values of x.
    y1.append(math.log(i))

# Evaluate x for corresponding values of x.
    y2.append(i)

# Evaluate x raised to the power x for corresponding values of x.
    y3.append(i ** 2)

# Plot the graphs
plt.figure(figsize =(16,5),dpi= 96)
plt.plot(X, y1, label = '$log_ex$')
plt.plot(X, y2, label = '$x$')
plt.plot(X, y3, label = '$x^2$')
# Label the x-axis
plt.xlabel("Base values  ------> ")
# Label the y-axis
plt.ylabel("Log Values   ------> ")
# Add a title to the graph
plt.title("A graph with  y={logex,x,x2}")
# Show a legend on the plot
plt.legend()
# Function to show the plot
plt.show()

"""**Q:** What are your observations?

**A:**  From the graph we can observe that the exponential curve increases much faster than a linear or logarithmic curve.

---

#### Activity 4: Plot a graph with $y=\{\log_e x, \log_e (x+4), \log_e x+4\}$

Calculate corresponding values for $y=\{\log_e x, \log_e (x+4), \log_e x+4\}$
and store them in variables `y1`, `y2`, and `y3`respectively.
"""

y1 = []
y2 = []
y3 = []
for i in X:
# Evaluate log(x) for corresponding values of x.
    y1.append(math.log(i))
# Evaluate log(x + 4) for corresponding values of x.
    y2.append(math.log(i + 4))
# Evaluate log(x) + 4 for corresponding values of x.
    y3.append(math.log(i) + 4)

# Plot the graphs
plt.figure(figsize=(16,5),dpi= 96)
plt.plot(X, y1, label = '$log_ex$')
plt.plot(X, y2, label = '$log_e(x+4)$')
plt.plot(X, y3, label = '$log_ex+4$')

# Label the x-axis
plt.xlabel("Base Values ------> ")
# Label the y-axis
plt.ylabel("Log Values  ------> ")
# Add a title to the graph
plt.title("A graph with  y={logex,loge(x+4),logex+4}")
# Show a legend on the plot
plt.legend()
# Function to show the plot
plt.show()

"""**Q:** What are your observations?

**A:** From the above curve we can observe that adding a constant to the log of a number has a high impact on the graph.

---

#### Activity 5: Plot a graph with $y=\{\log_e x,(\log_e (x))^2,\log_e (x^2)\}$

Calculate corresponding values for $y=\{\log_e x,(\log_e (x))^2,\log_e (x^2)\}$
and store them in variables `y1`, `y2`, and `y3`respectively.
"""

y1 = []
y2 = []
y3 = []
for i in X:
# Evaluate log(x) for corresponding values of x.
    y1.append(math.log(i))

# Evaluate log(x) raised to the power 2 for corresponding values of x.
    y2.append(math.log(i) **2)

# Evaluate log of x-squared for corresponding values of x.
    y3.append(math.log(i ** 2))

# Plot the graphs
plt.figure(figsize =(16,5),dpi = 96)
plt.plot(X, y1, label='$log_e$')
plt.plot(X, y2, label='$(log_ex) ^ 2$')
plt.plot(X, y3, label='$log_e(x^2)$')

# Label the x-axis
plt.xlabel("Base Values ------> ")
# Label the y-axis
plt.ylabel("Log Values  ------> ")
# Add a title to the graph
plt.title("A graph with  y={logex,(loge(x))2,loge(x2)}")
# Show a legend on the plot
plt.legend()
# Function to show the plot
plt.show()

"""**Q:** What are your observations?

**A:** From the above graph we can observe that squaring log x has a higher impact than the log of x square.

---

### Submitting the Project

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project75**) of the notebook will get copied.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project75** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""