# -*- coding: utf-8 -*-
"""Project 53

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6bw4XxDsENohM4F20JBQhCybgmAlkuz

### Instructions

---

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

 1. Classes and Objects

 2. Inheritance

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

    https://colab.research.google.com/drive/1DqpftdZmLCNJDXlITdeHS-15P2mDL1iH

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project53** format.

4. Now, write your code in the prescribed code cells.

---

### Problem Statement


An **Atom** is the smallest unit of matter that retains all of the chemical properties. An **Element** is a substance that is made entirely from one type of atom. For example, the element hydrogen is made from atoms containing a single proton and a single electron.


In this project, illustrate this hierarchical relationship of Atoms and  Elements using the concept of **Single-level Inheritance**.

---

### List of Activities

**Activity 1:** Create a parent class `Atom`.

  
**Activity 2:** Create an object of `Atom` class

**Activity 3:** Create a child class `Element` which inherits from the parent class `Atom`.

---

#### Activity 1: Create Parent class `Atom`

The following are some of the common properties of an atom:

|Property|Description|
|-|-|
|Name|Name of the atom|
|Protons|Positively charged particles of an atom in the nucleus|
|Electrons|Negatively charged particles of an atom in the outer shells|
|Neutrons|Neutral or empty charged particles of an atom in the nucleus|
|Electron Configuration|Distribution of electrons in the outer shells called orbits. For example: If there are 13 electrons, then the electron configuration will be [2, 8, 3].|
|Atomic Mass| It is approximately equal to the sum of the number of protons and neutrons in an atom|
|Net Charge|Difference in the number of protons and electrons.|

**Follow the steps given below:**

1. Create a class `Atom`. The constructor of this class must initialise the following variables:

- `name`: Name of the atom.

- `electrons`: Number of electrons.

- `protons`: Number of protons.

- `neutrons`: Number of neutrons.

- `electron_config`: A list representing distribution of electrons.

   
2. Add the following functions:

- `calculate_atomic_mass()`: Inside this function, calculate the value of `atomic_mass` variable by adding the number of protons and neutrons.

- `calculate_charge()`: Find the value of `net_charge` variable. Also, find out whether the atom is an anion, cation or neutral.

**Note:** The net charge of an atom is always **zero** as the number of protons and neutrons is equal in an atom. If the atom gains an extra electron, it becomes negatively charged and is known as an **anion**. If it loses an electron, it becomes positively charged and is known as a **cation**. Thus, `net_charge` is calculated as:

  `net_charge` = `protons` - `electrons`
"""

#  Create class 'Atom'. Add constructor and functions
class Atom:
    def __init__(self,name,protons,electrons,neutrons,electron_configuration):
        self.name = name
        self.electrons = electrons
        self.protons = protons
        self.neutrons = neutrons
        self.electron_configuration = electron_configuration

    def calculate_atomic_mass(self):
        atomic_mass = self.protons + self.neutrons
        return atomic_mass
    def calculate_charge(self):
        net_charge = self.protons - self.electrons

        if net_charge == 0:
           return "Neutral"
        elif net_charge < 0:
           return "Anion"
        elif net_charge > 0:
           return "Cation"

"""---

#### Activity 2: Create an Object of `Atom` Class

Create an object of `Atom` class having following properties:

|Property|Value|
|-|-|
|name|Aluminium|
|protons|13|
|electrons|13|
|neutrons|14|
|electron configuration|[2, 8, 3]|

Call the functions to calculate the atomic mass and find out whether it is an anion, cation or neutral.
"""

# Create an object of 'Atom' class and call the functions
Atom_1 = Atom("Aluminium",13,13,14,[2,8,3])
print(Atom_1.calculate_atomic_mass())
print(Atom_1.calculate_charge())

"""---

#### Activity 3: Create a Child Class `Element`


1. Create a child class `Element` which inherits from the parent class `Atom`. In addition to the properties of the parent class, the constructor of this class must initialise the following properties:

  - `mass`: Mass of the element.

  - `volume`: Volume of the element.

  - `melting_point`:  Melting point of the element.

  - `boiling_point`: Boiling point of the element.

2. After creating the child class, create its object and pass the attribute values of your choice. You can also use the following example:


|Property|Value|
|-|-|
|name|Aluminium|
|protons|13|
|electrons|10|
|neutrons|14|
|electron configuration|[2, 8]|
|mass|10800 kg|
|volume|4  $m^{3}$|
|boiling_point|2,743 K|
|melting_point|933.5K|

3. Call the functions to calculate the atomic mass and find out whether it is an anion, cation or neutral.
"""

# Create child class 'Element' and call the functions using the object of 'Element' class
class Element(Atom):
    def __init__(self,name,protons,electrons,neutrons,electron_configuration,mass,volume,boiling_point,melting_point):
        super().__init__(name,protons,electrons,neutrons,electron_configuration)
        self.mass = mass
        self.volume = volume
        self.boiling_point = boiling_point
        self.melting_point = melting_point

Element_1 = Element('Aluminium',13,10,14,[2,8],10800,4,2743,933.5)
print(Element_1.calculate_atomic_mass())
print(Element_1.calculate_charge())

"""---

### Submitting the Project:

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project53**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project53** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""