# -*- coding: utf-8 -*-
"""Project 76.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13b-KjihAEKj8aSBTM4RQ7RNIAOOVnZ0w

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in  Logistic Regression - Derivatives.

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

    https://colab.research.google.com/drive/1sZUNaESaMmo5RmfpPR3Q8S0YNi8Fl3SU

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project76** format.

4. Now, write your code in the prescribed code cells.

---

### Activities

#### Activity 1: Plot the Equation

In this activity, you need to plot the equation on the graph for the roller coaster.

$$y =  -0.000833 (x^3 + 12x^2 - 580x -1200) $$


Where,

- $y$ is the height of the roller coaster from the ground.

- $x$ is the horizontal length of the roller coaster


**Input**
* The input array should range from -30 to 30

**Steps**
1. Create the function to form the curve of the Roller Coaster with the equation given which takes an array as and returns the curve for the array.
2. Create an input array of 1000 numbers ranging from -30 to 30.
3. Call the function created for the curve with the input array created and save the output array returned in a new variable.
4. Plot the graph to display the path of the Roller Coaster using the input and output array.
"""

# Plot the curvature of the coaster using between x = -30 and x = 30 only.
# Import the modules.

import math
import numpy as np
import matplotlib.pyplot as plt

# Create the function to return the curve of the given equation for the input array/list

def curvature(X):
    return (-0.000833)*(X**3+12*X**2-580*X-1200)

# Create an input array
array = np.linspace(-30,30,1000)

# Call the function created for curve on the input array and save it in a new variable
curve = curvature(array)

# Plot the graph for the Roller Coaster

plt.figure(figsize=(21,5),dpi = 96)
plt.plot(array,curve)

# Plot a line x-axis, y-axis at (0,0)
plt.axvline(x = 0)
plt.axhline(y = 0)

# Create gridlines
plt.grid()

# Label both the axes
plt.xlabel('X-axis ------> ')
plt.ylabel('Y-axis ------> ')
plt.show()

"""----

#### Activity 2: Calculate and Plot the Derivative of the Equation

In this activity, you need to calculate the rate of change from the ground to
the top of the coaster using the derivative (or differentiation) equation and plot the graph for the same.

\begin{equation}
\frac{\delta y}{\delta x} = \frac{f(x + h) - f(x)}{h}
\end{equation}

$$ $$
\begin{equation}
\therefore \frac{\delta y}{\delta x} = \frac{y_i - y_{i-1}}{x_i - x_{i-1}}
\end{equation}


**Input**
* Use the input created in Activity 1


**Steps**
1. Create a function to calculate the derivative which takes two arrays - input array for x-axis and curvature array for y axis as and returns the derivative using the equation given for  $\delta y$.
2. Call the function created to calculate derivative with the input and output array created in the Activity 1 and save the derivative array returned in a new variable.
4. Plot the graph to display the rate of change in the path of the Roller Coaster using the input and derivative array.
"""

# Find the derivative and create the graph for the derivative of the input array created in Activity 1
# Create the function for finding the derivative of the input array

def derivative(array,curve):
    derivative_arr = [0.0]*len(array)
    for i in range(len(curve)-1):
        derivative_arr[i] = (curve[i+1] - curve[i]) / (array[i+1] - array[i])
    derivative_arr[-1] = (curve[-1] - curve[-2]) / (array[-1] - array[-2])
    return derivative_arr
derivative_arr = derivative(array,curve)

# Plot the derivative graph
plt.figure(figsize=(21,5),dpi = 96)
plt.plot(array,derivative_arr)

# Plot a line x-axis,y-axis at (0,0)
plt.axvline(x = 0.0,color = "green")
plt.axhline(y = 0.0,color = "red")

# Create gridlines
plt.grid()
# Labelling the axes
plt.xlabel("Delta y -------->")
plt.ylabel("Vertical Length -------> ")
plt.show()

"""**Hint**

Use a `for` loop to calculate the series for $\delta y$ from first i.e., $0^{th}$ element to second last i.e., ${n-2}^{th}$ and calculate the last element i.e. ${n-1}^{th}$ outside the loop

---

#### Activity 3: More Derivatives - Derivative of Log

In this acivity you have to plot the derivative of different logarithms
$$y=[\log_{10}x,\log_{10}2x,\log_{10}3x,\log_{10}5x,\log_{10}10x]$$

**Steps**
1. Create an input array of integers 1-100.
2. Calculate the different logarithms given in the question with respect to the input array and save them each in  another array/list.
3. Plot the graph for log terms.
4. Calculate the derivatives for the log terms with respect to the input array.
5. Plot the graph of the derivative of the log terms.

Create the graph for the different logarithm of the input array.
"""

# Create input for x-axis.
import math
x=[]
for i in range(1,101):
    x.append(i)
# Evaluate log(x) with base 10 for corresponding values of x.
y1=[]
for i in range(len(x)):
    y1.append(math.log(x[i],10))
# Evaluate log(2x) with base 10 for corresponding values of x.
y2=[]
for i in range(len(x)):
    y2.append(math.log(2*x[i],10))
# Evaluate log(3x) with base 10 for corresponding values of x.
y3=[]
for i in range(len(x)):
    y3.append(math.log(3*x[i],10))
# Evaluate log(5x) with base 10 for corresponding values of x.
y4=[]
for i in range(len(x)):
    y4.append(math.log(5*x[i],10))
# Evaluate log(10x) with base 10 for corresponding values of x.
y5=[]
for i in range(len(x)):
    y5.append(math.log(10*x[i],10))

# Plot the graphs for the logarithm

plt.figure(figsize=(21,5))

plt.plot(x,y1,label="logx")
plt.plot(x,y2,label="log2x")
plt.plot(x,y3,label="log3x")
plt.plot(x,y4,label="log5x")
plt.plot(x,y5,label="log10x")

# Add title to the graph

plt.title("---- Graph for logarithms ---")

# plot the graphs

# Labelling the axes
plt.xlabel("X-axis ------> ")
plt.ylabel("Y-axis ------> ")
# Show a legend on the plot
plt.legend()
# Show the plot
plt.show()

"""Create the graph for the different derivatives of the input array."""

# Plot the graphs for the derivatives of the logarithms

d1=derivative(x,y1)
d2=derivative(x,y2)
d3=derivative(x,y3)
d4=derivative(x,y4)
d5=derivative(x,y5)
plt.figure(figsize=(20,7))
# Plot the graphs
plt.plot(x,d1,label="derivative of log10x")
plt.plot(x,d2,label="derivative of log10 2x")
plt.plot(x,d3,label="derivative of log10 3x")
plt.plot(x,d4,label="derivative of log10 5x")
plt.plot(x,d5,label="derivative of log10 10x")
# Add title to the graph
plt.title("Graph for the derivatives of the logarithms")

# Labelling the axes
plt.xlabel("X-axis ------>  ")
plt.ylabel("Y-axis ------>  ")

# Show a legend on the plot
plt.legend()
# Show the plot
plt.show()

"""**Q:** What are your observations?

**A:** From the above graph, we can see that when the base  b  is less than 1, the graph of a log function continuously decreases as the values on the  x -axis increase.

Here, the graph of a log function drops very sharply for the initial values of  x . As the  x  values start increasing from a particular point, the curve starts flattening.

---

### Submitting the Project

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project76**) of the notebook will get copied.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project76** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""