# -*- coding: utf-8 -*-
"""Project 86.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qc1uWtW8EvuQ_KU04MpdlvfsZcf8p-Va

### Instructions

#### Goal of the Project
This project is designed for you to practice and solve the activities that are based on the concepts covered in the lesson:

   Support Vector Machines - MNIST Digits Classification

---

#### Problem Statement

In this project, you are going to revise the lesson by visualising the images from linear sequences.

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

     https://colab.research.google.com/drive/1Q_65eybSFJ6dCCmb7xkux72tkLBu2I1H  

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project86** format.

4. Now, write your code in the prescribed code cells.

---

###**Image Description**

You need to recreate the image given below using its pixels.

<center><img src = "https://s3-whjr-v2-prod-bucket.whjr.online/bd7cbe01-f020-4c66-84f1-1ff53ffbe393.jpg" width = 400 height=400></center>

<center><b>Image Credits:</b> Photo by <a href="https://unsplash.com/@hyperblue?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Henning Gärtner</a> on Unsplash </center>

  


The image is a 24-bit RGB PNG image (8 bits for each of R, G, B). So the number of pixels will be: $$ pixels = height \times width \times 3$$

Where height and width are the dimensions of the image.

---

### Activities


**Activity 1:** Read the Image File.

**Activity 2:** Display the Image.

---

#### Activity 1: Read the Image file

In this activity, you need to execute a code cell which will read the image file from the link given using the `imread()` function.

The basic syntax for the `imread()` function in the `matplotlib.pyplot` module is:

>**Syntax:** `matplotlib.pyplot.imread(path)`

Where,
- `path`: address path of the image to be read.

The output of the `imread()` function is an array of shape `(height, width, dimension)`.

**Note:** The `dimension` is based on the type of image. In this case the `dimension` will be `3` as we already know image includes 8 bits each of R, G and B.

The steps to be followed are:

**1.** Execute the below code section to read the image.
"""

# Run this code cell to read the image file

import matplotlib.pyplot as plt

img = plt.imread('https://s3-whjr-v2-prod-bucket.whjr.online/71d278a3-604d-4f24-a6a4-4e09f0ae11ca.png')
print(img)

"""As it can be observed, a sequence gets created for storing the pixel values of the image.

---

**2.** Verify the type of the output variable and it's shape.
"""

# Print the type and shape of the image variable created.
print(f"{type(img)}")
print(f"{img.shape}")

"""**Q:** Looking at the shape of the output, what is the height and width of the image?

**A:** The shape of the output is  1213 and 560 ,the height and width of the image respectively.

**After this activity, the image file should be converted into an array of pixels.**

----

#### Activity 2: Display the Image

In this activity, you have to display the image using the `matplotlib.pyplot.imshow()` function using different parameters.

**1.** Display the image using the default parameters set for the `imshow()` function.
"""

# Display the image using the default parameters
plt.figure(figsize=(8,8),dpi = 96)
plt.imshow(img)
plt.show()

"""**2.** Display the image by adding the `cmap ="gray"` to try and display the image in grayscale."""

# Display the image using the cmap parameter
plt.figure(figsize=(6,6),dpi = 96)
plt.imshow(img,cmap='gray')
plt.show()

"""**Q** Is there any change in the image display?

**A** No

---

**3.** Display the image in 2D format. For that, pass `img[:,:,0]` parameter inside `imshow()` function:
"""

# Display the image using the cmap parameter
plt.figure(figsize=(8,8))
plt.imshow(img[:,:,0])
plt.show()

"""**Q** Is there any change in the image display?

**A** Yes



---

**4.** Display the image with two dimension and the `cmap ="gray"` to try and display the image in grayscale.


"""

# Display the image in two dimension and cmap='gray' parameter.
plt.figure(figsize=(8,8))
plt.imshow(img[:,:,0],cmap='gray')
plt.show()

"""**Q:** Is the image displayed in grayscale?

**A:** Yes

**After this activity, the image file should be displayed in 2D format as well as in grayscale.**

---

### Submitting the Project

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project86**) of the notebook will get copied.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project86** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""