# -*- coding: utf-8 -*-
"""project 83.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w0IAR4DkRAPC9TgdxqO11r9n4rgOidZG

### Instructions

#### Goal of the Project
This project is designed for you to practice and solve the activities that are based on the concepts covered in the lesson:

Support Vector Machines - Hyperplane Visualisation I

---

#### Problem Statement

In this project, you are going to revise the lesson by creating and visualizing mesh grid and contours.

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

     https://colab.research.google.com/drive/1Jelj0ekz6esRIkUIK2BQlau2F9xBC-UA  

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project83** format.

4. Now, write your code in the prescribed code cells.

---

### Activities


**Activity 1:** Create a Mesh Grid

**Activity 2:** Create a Contour Plot

---

####Activity 1: Create a Mesh Grid

Create a mesh grid for two different one-dimensional arrays using the steps below:

1. Create a variable `x` for creating a NumPy array from range `-3.0` to `3.0` and step size as `0.50`.
2. Create a variable `y` for creating a NumPy array from range `-2.0` to `2.0` and step size as `0.50`.
3. Create a meshed grid using `meshgrid()` function from the two arrays `x` and `y` and two-dimensional output arrays in `xx_values` and `yy_values` variable.
4. Create a scatter plot for the two-dimensional arrays using the customization given below:
  - style: `seaborn`
  - marker: `o`, colour = green
  - grid lines: `major`, both axes, style = `dashed`, colour = `red`
  
5. Create annotations for the coordinates in the scatter plot.

6. Display the graph.
"""

# Create and visualize a mesh grid.
# Import the libraries
import numpy as np
import pandas as pd
from sklearn.svm import SVC
import matplotlib.pyplot as plt

# Create one dimensional 'x' and 'y' arrays
X = np.arange(-3,3,0.50)
y = np.arange(-3,3,0.50)
# Create the mesh grid
XX_values,yy_values = np.meshgrid(X,y)
# Create the graph plot
plt.figure(figsize=(20,5),dpi = 96)
# Allot the style
plt.style.use('seaborn')
# Create the scatter plot
plt.scatter(XX_values,yy_values,marker= 'o',color = 'green')
plt.grid(which = 'major',axis ='both',linestyle = 'dashed',color = 'red')
# Create the annotations
for i in X:
    for j in y:
        plt.annotate(s=f"{i} {j}", xy = (i + 0.1, j))
# Display the graph
plt.show()

"""**Hint:** For customization of the graph, recall lesson **42:
Air Quality Analysis - Customised matplotlib Plots.**

**After this activity, a mesh grid plot should be created and annotated.**

---

####Activity 2: Create a Contour Plot

Create a contour plot for two one dimensional arrays and using the equation for `z`:

1. Create a variable `x` for creating a NumPy array from range `-3.0` to `3.0` and step size as `0.025`.
2. Create a variable `y` for creating a NumPy array from range `-2.0` to `2.0` and step size as `0.025`.
3. Create a meshed grid using `meshgrid()` function from the two arrays `x` and `y` and two-dimensional output arrays in `xx_values` and `yy_values` variable.
4. Create the `zz_values` array for the z-axis using the 3 formulas below:
   $$z_1 = e^{-xx^2 - yy^2} $$
   $$z_2 = e^{-(xx-1)^2 - (yy-1)^2} $$
   $$zz = (z_1-z_2)2 $$
5. Create a contour plot with `xx_values`, `yy_values`, and `zz_values` arrays with the gaps filled with colour using the customization given below:
  - style: `grayscale`
  - colour map: `coolwarm_r`
  - alpha: `1`
  
6. Display the colour bar.

7. Display the graph.
"""

from operator import contains
import numpy as np
# Create and visualize a contour.
# Create one dimensional 'x' and 'y' arrays
X = np.arange(-3.0,3.0,0.025)
y = np.arange(-2.0,2.0,0.025)
# Create the mesh grid
xx_values ,yy_values = np.meshgrid(X,y)
# Create 'zz' array
z1 = np.exp(-(xx_values)**2 - (yy_values)**2)
z2 = np.exp(-(xx_values-1)**2 - (yy_values-1)**2)
zz_values = (z1 - z2)**2
# Create the graph plot
plt.figure(figsize=(20,5),dpi = 96)
# Allot the style
plt.style.use('grayscale')
# Create the contourf graph
plt.contourf(xx_values,yy_values,zz_values,cmap = plt.cm.coolwarm_r,alpha=1)
# Display the colorbar
plt.colorbar()
# Display the graph
plt.show()

"""**After this activity, a contour plot should be created for the given equation.**

---

### Submitting the Project

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project83**) of the notebook will get copied.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project83** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""