# -*- coding: utf-8 -*-
"""Project 63.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bf1hPj4MJtyAhBO9af5NIDmeGnbxBnoe

### Instructions

---

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lesson:

 1. Multiple linear regression - Introduction

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

  https://colab.research.google.com/drive/1VFztldc1Q2bIfw9qUMlzPaRMgXyiIR6N

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project63** format.

4. Now, write your code in the prescribed code cells.

---

### Problem Statement

Many of your friends are worried about their chances of getting admission in their dream university for pursuing MS. So, you decided to help them by building a model which is capable of predicting their chance of getting admission in their dream masters program. This model will also help in understanding which factors are important in MS admissions and what are the scores required for different tests to have better admission chances.

Build a prediction model using multiple linear regression to predict the likelihood of getting admission and evaluate the accuracy of the model.

---

### List of Activities

**Activity 1:** Analysing the Dataset

**Activity 2:** Finding Correlation
  
**Activity 3:** Train-Test Split

**Activity 4:**  Model Training

**Activity 5:** Model Prediction

**Activity 6:** Model Evaluation

---

#### Activity 1:  Analysing the Dataset

- Create a Pandas DataFrame for **Admission_Predict** dataset using the below link. This dataset consists of several parameters which are considered important during the application for Masters program:


|Field|Description|
|---:|:---|
|Serial No.|Serial No.|
|GRE Score|GRE Scores ( out of 340 )|
|TOEFL Score|TOEFL Scores ( out of 120 )|
|University Rating|University Rating ( out of 5 )|
|SOP|Statement of Purpose Strength ( out of 5 )|
|LOR|Letter of Recommendation Strength ( out of 5 )|
|CGPA|Undergraduate GPA ( out of 10 )|
|Research|Research Experience ( either 0 or 1 )|
|Chance of Admit|Chance of Admit ( ranging from 0 to 1 )|



  **Dataset Link:** https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/Admission_Predict.csv

- Print the first five rows of the dataset. Check for null values and treat them accordingly.

- Also drop the column `Serial No.` from the dataset as it is of no use for analysis. Check whether the column names contain any trailing and leading spaces. If yes, remove the whitespaces from the column names.

**Hint:** You can use `strip()` and `rename()` functions to remove unwanted whitespaces from the column name and to rename them.
"""

# Import modules
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
# Load the dataset
# Dataset Link: 'https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/Admission_Predict.csv'
df = pd.read_csv("https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/Admission_Predict.csv")
# Print first five rows using head() function
df.head()

# Check if there are any null values. If any column has null values, treat them accordingly
df.isnull().sum()

# Get the list of columns of the dataset.
df.columns

df.head()

# Drop 'Serial No.' column from the DataFrame
df=df.drop(columns = ['Serial No.'])
df.columns

# Remove whitespaces from both ends in the column name if there are any
for column in df.columns :
    df.rename(columns={column:column.strip()},inplace=True)

# Get list of all the columns after renaming.

df.columns

"""---

#### Activity 2: Finding Correlation

We need to predict the value of `Chance of Admit` variable, given other variables. Thus, `Chance of Admit` is the target variable and other columns except `Chance of Admit` are the feature variables.

Find the columns that are highly correlated with the `Chance of Admit` column. For this, calculate the correlation coefficient values between all the columns and then use a heatmap to visualize these correlations.
"""

# Calculate correlation coefficient for all columns of the DataFrame
import seaborn as sns
corr_df = df.corr()
# Use heatmap to observe correlations.
plt.figure(figsize=(20,5))
sns.heatmap(corr_df,annot=True)
plt.show()

"""**Q:** On observing the heatmap, which three scores seems most important for getting admission in an MS program?

**A:**  GRE Score , TOEFL Score and CGPA are the three scores which seems to be the most important for getting admission in an MS program.

---

#### Activity 3: Train-Test Split


Split the dataset into training set and test set such that the training set contains 70% of the instances and the remaining instances will become the test set.
"""

# Split the DataFrame into the training and test sets.
from sklearn.model_selection import train_test_split
features = df.columns.values[:-1]
X = df[features]
y = df['Chance of Admit']
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size= 0.33,random_state=42)

"""---

#### Activity 4: Model Training

Implement multiple linear regression using `sklearn` module by creating an object of the `LinearRegression` class and calling the `fit()` function.

**Note:** Reshaping the target variable array into a 2D array is not mandatory in multiple linear regression. You can skip that.
"""

# Build linear regression model
from sklearn.linear_model import LinearRegression
y_train_reshaped = y_train.values.reshape(-1,1)
y_test_reshaped = y_test.values.reshape(-1,1)
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train_reshaped)

# Print the value of the intercept
print('Intercept is:',lin_reg.intercept_[0])

# Print the names of the features along with the values of their corresponding coefficients.
for item in list(zip(X.columns.values,lin_reg.coef_[0])) :
    print(f"{item[0]}".ljust(15, " "), f"{item[1]:.6f}")

"""---

#### Activity 5: Model Prediction using Test Set

Predict the values for the test set by calling the `predict()` function on the LinearRegression object.

Also, predict your friend's chances of getting admission into his dream university with a GRE score of 350, TOEFL score of 115, University Rating of 3, SOP of score 3, 3 LORs, CGPA of 9.8 and having research papers.

**Note:** Pass the values of all feature variables to the `predict()` function in the form of a 2D array as follows:

`predict([[350, 115, 3, 3, 3, 9.8, 1]])`
"""

# Predict the target variable values for test set
y_test_pred = lin_reg.predict(X_test)

# Make new prediction for your friend
y_friend_prediction = lin_reg.predict([[350,115,3,3,3,9.8,1]])
print(y_friend_prediction)

"""**Q:** How much is your friend's chance of getting admission for MS?

**A:** My friend has a 97% chance of getting admission for MS.

---

#### Activity 6: Model Evaluation

Calculate the $R^2$, MSE, RMSE and MAE values for the test set to evaluate the accuracy of your model.
"""

# Evaluate the model using the 'r2_score', 'mean_squared_error' & 'mean_absolute_error' functions of the 'sklearn' module for the test set.
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
print('R-squared:',r2_score(y_test_reshaped, y_test_pred))
print('Mean squared error:',mean_squared_error(y_test_reshaped, y_test_pred))
print('Root mean squared error:',np.sqrt(mean_squared_error(y_test_reshaped,y_test_pred)))
print('Mean absolute error:',mean_absolute_error(y_test_reshaped, y_test_pred))

"""---

### Submitting the Project:

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project63**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project63** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""