# -*- coding: utf-8 -*-
"""Project 55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kunZpeYxtGthP6wraJ-V1DL6QbiWrfLV

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

 1. Python Dictionary

 2. Classes and Objects

 3. Encapsulation

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

    https://colab.research.google.com/drive/1zvCUZ13FqEnatGnafkz72X5_zutg66h9?authuser=3

2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project55** format.

4. Now, write your code in the prescribed code cells.

---

### Problem Statement


In this project, create a small Hospital Management application using the concept of **Object Oriented Programming**.

Ask the user to enter a number from 1, 2, 3, 4, or 9. These numbers indicate the following options:

  - **1: Display List of all Doctors** $\Longrightarrow$ Displays a list of all the doctors in the hospital and their specialty.

  - **2: Display List of all Patients** $\Longrightarrow$ Displays a list of all the patients in the hospital and the disease from which they are suffering.

  - **3: Add a Doctor** $\Longrightarrow$ Adds a new doctor.

  - **4: Add a Patient** $\Longrightarrow$ Adds a new patient.
    
  - **9: Quit** $\Longrightarrow$ Quits the application.

---

### List of Activities

**Activity 1:** Create a class `Doctor`.

**Activity 2:** Create a class `Patient`.

**Activity 3:** Create Objects and Call the Functions

---

#### Activity 1: Create a class `Doctor`

1. Create a class `Doctor`. Inside this class, create a dictionary to store the name of doctors (as key) and their specialisations (as its value).

2. The constructor of the class `Doctor` must initialise the following **private** variables:

  - `emp_id`: Employee id of the doctor.

  - `name`: Name of the doctor.

  - `salary`: Salary of the doctor.

  - `specialisation`: Specialisation of the doctor.

2. The constructor should also call a **class method** `add_doctor()` which will add the newly created object of `Doctor` class to the dictionary.
   
3. Add getter functions for each of the private variables and 1 setter function to update the salary.

4. Add one more class method to simply display the list of doctors and their specialisations by displaying the contents of the dictionary.
"""

#  Create class 'Doctor'. Add constructor, getter functions and class methods
class Doctor:
    doctors = {}
    def __init__(self, emp_id, name, salary, specialisation):
        self.__emp_id = emp_id
        self.__name = name
        self.__salary = salary
        self.__specialisation = specialisation
        Doctor.add_doctor(self.__emp_id, self.__name, self.__salary, self.__specialisation)

    @classmethod
    def add_doctor(cls, emp_id, name, salary, specialisation):
        cls.doctors.update({name : specialisation})
        return f'new added doctor: {name} - {specialisation} successfully!'

    def get_doc_name(self):
        return self.__name.title()

    def get_emp_id(self):
        return self.__emp_id

    def get_salary(self):
        return self.__salary

    def get_specialisation(self):
        return self.__specialisation

    @classmethod
    def display_doctors(cls):
        return cls.doctors

    def set_salary(self, amount):
        self.__salary = amount
        return self.__salary

"""####Activity 2: Create a class `Patient`

1. Create a class `Patient`.  Inside this class, create a dictionary to store the name of patients (as key) and their disease (as its value).

2. The constructor of the class `Patient` must initialise the following **private** variables:

  - `name`: Name of the patient.

  - `age`: Age of the patient.

  - `disease`: Disease of the patient.

3. The constructor should also call a **class method** `add_patient()` which will add the newly created object of `Patient` class to the dictionary.
   
3. Add getter functions for each of the private variables.

4. Add one more class method to simply display the list of patients and their disease by displaying the contents of the dictionary.
"""

#  Create class 'Patient'. Add constructor and functions
class Patient:
    patients = {}
    def __init__(self,name,age,disease):
        self.__name = name
        self.__age = age
        self.__disease = disease
        patients.add_patients(self.__name,self.__age,self.__disease)

    @classmethod
    def add_patients(cls,name,age,disease):
        cls.patients.update({name : age })
        return f'New added  Patients: {name} - {age} - {disease} successfully !'

    def get_patient_name(self):
        return self.__patients

    def get_age(self):
        return self.__age

    def get_disease(self):
        return self.__disease



    @classmethod
    def display_patients(cls):
        return cls.patients

"""---

#### Activity 3: Create Objects and Call the Functions

Initialise a variable `empid` with any value of your choice. Create an infinite `while` loop. Inside this `while` loop perform the following tasks:
1. Display the following list of choices:

```
Enter :
        1 to Display all the Doctors and their Specialisations
        2 to Display the list of patients and their disease
        3 to Add a Doctor
        4 to Add a Patient
        9 to QUIT the application
```

2. Take user input and store it in a variable `user_choice`. Check whether the user entered any input other than 1, 2, 3, 4 or 9. If yes, then display a message "Please enter a valid option" and keep on asking for user input unless the user enters a valid choice.

3. Now using the `if-elif-else` statement, check user input and perform the following tasks:

  - If `user_choice==1`, call the class method of `Doctor` class which displays the list of doctors along with their specialisation.

  - If `user_choice==2`, call the class method of `Patient` class which displays the list of patients along with their disease.

  - If `user_choice==3`, ask the user to enter the name, salary, specialisation of the doctor and create an object of `Doctor` class by passing the entered details. Also increment the value of the `empid` variable and pass it while creating the object of `Doctor` class.
      * Print the data of the newly created object using getter functions of `Doctor` class.
      * Ask the user if it wishes to update the salary of the doctor. If yes, then call the setter function of the private variable `salary` to modify the salary of the doctor.

  - If `user_choice==4`, ask the user to enter the name, age, disease of the patient and create an object of `Patient` class by passing the entered details. Print the data of the newly created object using getter functions of the `Patient` class.
  - If `user_choice==9`, break the infinite while loop using the `break` statement.
"""

# Create infinite while loop
print("""Enter :
        1 Display all the Doctors and their Specialisations
        2 Display the list of patients and their disease
        3 to Add a Doctor
        4 to Add a Patient
        9 to QUIT the application""")

emp_id = 0
while True:
    user_choice = input('Enter your choice here : ')
    user_choice = int(user_choice)

    if user_choice == 1:
        doctors = Doctor.display_doctors()
        print("""The doctors in the hospital are:  \n kalyan : Allergists and Immunologists
                                                   \n ajay   : Anesthesiologists
                                                   \n anand : Cardiologists
                                                   \n neha  : Colon and Rectal Surgeons """)
        for k,v in doctors.items():
            print(k , " : ", v)


    elif user_choice == 2:
        patients = Patient.display_patients()
        print("""  The patients in the hospital are:  \n aniket  : jaundis
                                                      \n harsh   : fever
                                                      \n babita  : fungus
                                                      \n arya    : typhoid """)
        for k,v in patients.items():
            print(k, " : ", v)



    elif user_choice == 3:
        doc_name = input('Enter doctor name: ')
        doc_salary = int(input('Enter doc salary: '))
        doc_specialisation = input('Enter specialisation: ')
        emp_id += 1
        new_doc = Doctor(emp_id, doc_name, doc_salary, doc_specialisation)
        print(  f' Doctor name   : {new_doc.get_doc_name()} \
                \n Doctor ID     : {new_doc.get_emp_id()} \
                \n Doctor Salary : {new_doc.get_salary()} \
         \n Doctor Specialisation: {new_doc.get_specialisation()}')
        print('Enter A to Modify salary details? else press any key \n ')
        yes_or_no = input()
        if yes_or_no == 'A' or yes_or_no == 'a':
            salary = input('Enter the new salary for the doctor : ')
            updated_salary = new_doc.set_salary(salary)
            print(f'Updated Salary for {new_doc.get_doc_name()} is Rs. {new_doc.get_salary()}')

    elif user_choice == 4:
        patient_name = input("Enter patient's name : ")
        patient_age = int(input('Enter age of patient :'))
        patient_disease = input('Enter disease of patient : ')

        new_patient = Patient(patient_name, patient_age, patient_disease)
        print( f'Patient Name:    {new_patient.get_patient_name()} \
              \n Patient Age:     {new_patient.get_age()} \
              \n Patient Disease: {new_patient.get_disease()}')


    elif user_choice == 9:
        print("---Thanks to know our information with help of us -------")
        break
    else:
        print('please enter a valid option ')

"""---

### Submitting the Project:

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>

3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project55**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.
   
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project55** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>

---
"""

num = int(input("enter a number :"))
num
print(type(num))